BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Dragao] (
    [id] INT NOT NULL IDENTITY(1,1),
    [nome] NVARCHAR(1000) NOT NULL,
    [cor] NVARCHAR(1000) NOT NULL,
    [montador] NVARCHAR(1000) NOT NULL,
    [vivo] BIT NOT NULL CONSTRAINT [Dragao_vivo_df] DEFAULT 1,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Dragao_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Dragao_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
